services:
  whatsapp_go:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    build:
      context: .
      dockerfile: ./docker/golang.Dockerfile
    restart: 'always'
    ports:
      - "${PORT}:3000"
    environment:
      - OS_NAME=${OS_NAME}
      - BASIC_AUTH=${BASIC_AUTH}
      - PORT=3000
      - DEBUG=${DEBUG}
      - AUTOREPLY=${AUTOREPLY}
      - WEBHOOK=${WEBHOOK}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - PROXY_URL=${PROXY_URL}
    command: >
      --debug=${DEBUG}
